### ISSUE TITLE
Getting "java.lang.NoSuchMethodError" while performing applitools eyes check validation for Mobile app

### ISSUE THREAD

**Issue by bhangeprashant** [innovativeQALab/iqa-automation-framework#44]
INFO  TestNGMethodInvocationListener - ******** In before invocation
INFO  CustomProperties - Property 'platform' fetched from System environment variable
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 33.364 sec <<< FAILURE!
runScenarios(org.iqa.test.runner.ParallelTestRunner)  Time elapsed: 32.402 sec  <<< FAILURE!
java.lang.NoSuchMethodError: com.applitools.eyes.selenium.ClassicRunner.<init>(Ljava/lang/String;Ljava/lang/String;)V
	at com.applitools.eyes.appium.AppiumRunner.<init>(AppiumRunner.java:21)
	at com.applitools.eyes.appium.Eyes.<init>(Eyes.java:32)
	at org.iqa.suite.commons.applitool.ApplitoolEyesMobile.createEyes(ApplitoolEyesMobile.java:74)
	at org.iqa.test.base.BaseTest.openApplitoolEye(BaseTest.java:142)
	at org.iqa.test.runner.ParallelTestRunner.runScenarios(ParallelTestRunner.java:29)

**Comment by bhangeprashant** [comment]
This is resolved. Hence closing this issue.
